version: '3.8'
services:
    nestjs:
      container_name: nestjs_api
      image: nestjs-api
      build:
          context: .
      command: sh -c "npm i && npm run start:dev"
      ports:
          - ${PORT}:${PORT}
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: always
      depends_on:
          - db_api

    db_api:
      image: mysql:8.0.14
      container_name: db_api
      ports: 
        - 3306:3306
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
volumes:
  db_data: {}
